name: Verify library
on:
  push:
    branches: [ main ]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Dependencies OK
        run: npm ci
      - name: Library builds
        run: npm run build 
      - name: Code quality OK
        run: npm run lint
      - name: Tests OK
        run: npm run test